books/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
                       url('^add/(\w+)/$', 'archbooks.books.views.add', name='books_add'),
                       url('^show/(\w+)/(\d*)/*', 'archbooks.books.views.show'),
                       url('^show/(\w+)/$', 'archbooks.books.views.show', name='books_show'),
                       url('^edit/(\w+)/(\d+)/$', 'archbooks.books.views.edit'),
                       url('^ratebook/(?P<id>\d+)/(?P<up_or_down>[\+-])/$', 
                           'archbooks.books.views.rate_book', name='rate_book'),
                       url('^get_isbn/$', 'archbooks.books.views.get_isbn'),
                       )

urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       (r'^accounts/', include('registration.urls')),
                       (r'^accounts/', include('archbooks.users.urls')),
                       (r'^books/', include('archbooks.books.urls')),
                       ('^admin/(.*)$', admin.site.root),
                       (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': '/home/ben/Projects/Django/archbooks/media/', 'show_indexes': True}),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/(.*)', admin.site.root),
)

books/models.py
from django.db import models
from django.contrib.auth.models import User

from fields import ISBNFormField

class ISBNField(models.CharField):
    def __init__(self, book_title, *args, **kwargs):
        self.book_title = book_title
        kwargs['max_length'] = 13
        super(ISBNField, self).__init__(*args, **kwargs)

    def formfield(self, **kwargs):
        # This is a fairly standard way to set up some defaults
        # while letting the caller override them.
        #kwargs['book_title_field'] = self.book_title
        defaults = {'form_class': ISBNFormField}
        defaults.update(kwargs)
        return super(ISBNField, self).formfield(**defaults)


class BookModel(models.Model):
    created_by = models.ForeignKey(User, related_name='created_by_user_%(class)s')
    
    class Meta:
        abstract = True


class Genre(BookModel):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)
    
    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        ordering = ["name",]


class Author(BookModel):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

    class Meta:
        ordering = ["last_name",]


class Series(BookModel):
    name = models.CharField(max_length=100)
    
    def __unicode__(self):
        return u'The %s Series' % (self.name)

    class Meta:
        ordering = ["name",]
        verbose_name_plural = "Series"


class Book(BookModel):
    title = models.CharField(max_length=50)
    authors = models.ManyToManyField(Author)
    ISBN = ISBNField(title, help_text="Fill in the title and author,\
 then click '...' to autofill isbn and optionally, blurb")
    series = models.ForeignKey(Series, blank=True, null=True)
    genre = models.ForeignKey(Genre)
    blurb = models.TextField()
    positive_ratings = models.IntegerField(default=0)
    negative_ratings = models.IntegerField(default=0)
    #ISBN = models.CharField(max_length=20) #should be an isbn field
    amazon_link = models.URLField(blank=True)
    bookchan_link = models.URLField(blank=True)
    rated_by = models.ManyToManyField(User, blank=True)
    cover_image = models.ImageField(upload_to='book_coverimages', blank=True)
    cover_image_authenticated = models.BooleanField(blank=False)
    
    def __unicode__(self):
        return self.title
    
    def get_rating_percentage(self):
        positive_ratings, negative_ratings = self.positive_ratings, self.negative_ratings
        if positive_ratings == 0 and negative_ratings == 0:
            return u'50%'
        else:
            return u'%i%%' % ((float(positive_ratings) / (positive_ratings + negative_ratings))*100)
    
    def get_authors(self):
        return u', '.join([str(author) for author in self.authors.all()])

    class Meta:
        ordering = ["title",]
        permissions = (
            ("can_authenticate_picture", "Can authenticate picture"),
        )


class Review(BookModel):
    RATING_CHOICES = (
        (0, 'pathetic'),
        (1, 'could have been worse'),
        (2, 'not great'),
        (3, 'mediocre'),
        (4, 'enjoyable'),
        (5, 'best thing evarr')
        )
    for_book = models.ForeignKey(Book)
    rating = models.SmallIntegerField(choices=RATING_CHOICES)
    review_contents = models.TextField()

books/forms.py
from django.forms import ModelForm
from django.forms.util import ErrorList

from isbndb import IsbnDB
from models import *

db = IsbnDB()

class BookObjectForm(ModelForm):
    class Media:
        js = ('form_functions.js',)


class GenreForm(BookObjectForm):
    class Meta:
        model = Genre
        exclude = ['created_by',]
        get_autofill = []


class AuthorForm(BookObjectForm):
    class Meta:
        model = Author
        exclude = ['created_by',]
        get_autofill = []


class SeriesForm(BookObjectForm):
    class Meta:
        model = Series
        exclude = ['created_by',]
        get_autofill = []


class BookForm(BookObjectForm):

    def clean(self):
        cleaned_data = self.cleaned_data
        title = cleaned_data.get("title")
        isbn = cleaned_data.get("ISBN")

        if title and isbn:
            if not db.validate_isbn(isbn, title):
                error_message = "That isbn doesn't correspond \
                        with the title of the book, or is invalid."
                self._errors['ISBN'] = ErrorList([error_message])
                del cleaned_data['ISBN']
        # Always return the full collection of cleaned data.
        return cleaned_data

    class Meta:
        model = Book
        exclude = ['created_by', 'positive_ratings', 'negative_ratings', 'rated_by', 'cover_image_authenticated']
        get_autofill = []


class ReviewForm(BookObjectForm):
    class Meta:
        model = Review
        exclude = ['created_by',]
        get_autofill = [('for_book', int),]

books/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.views.generic import list_detail

from decorators import login_required_ajax
from forms import GenreForm, AuthorForm, SeriesForm, BookForm, ReviewForm
from isbndb import IsbnDB
from models import Genre, Author, Series, Book, Review


modeldict = {'book': (Book, BookForm),
             'author': (Author, AuthorForm),
             'genre': (Genre, GenreForm),
             'series': (Series, SeriesForm),
             'review': (Review, ReviewForm)
             }
linkedfields = {'authors': 'author',
                 'series': 'series',
                 'genre': 'genre',
                 'for_book': 'book',
                 }
specialfields = {'ISBN': ('archbooks.books.views.get_isbn', 
                          [], 
                          "?book_title=' + document.getElementById('id_title').value + '&author=' + getTextOfSelectedOption(\'id_authors\') + '")}

isbn_db = IsbnDB()

@login_required
def add(request, add_what = None):
    if add_what not in modeldict:
        raise Http404
    model, modelform = modeldict[add_what]
    popup = request.GET.get('popup', None)
    if request.method == 'POST':
        form = modelform(request.POST, request.FILES)
        if form.is_valid():
            saved = form.save(commit=False)
            saved.created_by = request.user
            saved.save()
            try:
                form.save_m2m()
            except AttributeError:
                pass #Not all forms need, and hence have, a save_m2m() method
            if popup:
                return render_to_response('books/popup_close.html',
                                          RequestContext(request,
                                                         {'added_what': saved,
                                                          'popup': popup
                                                          }
                                                         )
                                          )
            else:
                request.user.message_set.create(message='%s Added Successfully' % add_what.title())
                return render_to_response('books/done.html',
                                          RequestContext(request,
                                                         {'added_what': saved,
                                                          'what_is_it': add_what
                                                          }
                                                         )
                                          )
    else: #form not already created - make one!
        initial_values = {}
        for autofill, function in modelform.Meta.get_autofill:
            if callable(function):
                try:
                    initial_values[autofill] = function(request.GET.get(autofill, ''))
                except TypeError:
                    pass #if value doesn't go with the function passed, then 'taint so ignore
                except ValueError:
                    pass
        #print "initial values are", initial_values
        form = modelform(initial=initial_values)
    return render_to_response('books/add.html',
                              RequestContext(request,
                                             {'adding_what': add_what.title(),
                                              'form': form,
                                              'linked': linkedfields,
                                              'specials': specialfields,
                                              }
                                             )
                              )


def show(request, show_what, id=None):
    if show_what not in modeldict:
        raise Http404
    model = modeldict[show_what][0]
    if not id:
        page = request.GET.get('page', '1')
        if page != 'last':
            try:
                page = int(page)
            except ValueError:
                page = 1

        list_info = {
            'queryset' :   model.objects.all(),
            'allow_empty': True,
            'paginate_by': 3, #make this configurable maybe
            'page': page,
            } # no clue why this is here, delete or use?
        return list_detail.object_list(request,
                                       queryset=model.objects.all(),
                                       allow_empty=True,
                                       paginate_by=3,
                                       page=page
                                       )

    else:
        if model.objects.filter(id=id).count():
            return list_detail.object_detail(request,
                                             queryset=model.objects.all(),
                                             object_id=id,
                                             template_object_name=show_what,
                                             )
        else:
            raise Http404


@login_required
def edit(request, edit_what, id):
    print request
    if edit_what not in modeldict:
        raise Http404
    model,modelform = modeldict[edit_what]
    modelinstance = get_object_or_404(model, id=id)
    if not (modelinstance.created_by == request.user or request.user.has_perm('books.change_book')):
        request.user.message_set.create(message='You don\'t have permission to do that! Tisk tisk...')
        return HttpResponseRedirect(reverse(show, args=[edit_what, id]))
    if request.method == 'POST':
        form = modelform(request.POST, request.FILES,instance=modelinstance)
        if form.is_valid():
            if edit_what == 'book':
                if modelinstance.cover_image:
                    modelinstance.cover_image.delete()
            added_what = form.save()
            return render_to_response('books/done.html',
                                      RequestContext(request, 
                                                     {'added_what': added_what,
                                                      'what_is_it': edit_what
                                                      }
                                                     )
                                      )
    else:
        form = modelform(instance=modelinstance)
    return render_to_response("books/add.html", 
                              RequestContext(request,
                                             {'form': form,
                                              'specials': specialfields,
                                              'linked': linkedfields,
                                              'adding_what': edit_what.title(),
                                              }
                                             )
                              )


@login_required_ajax
def rate_book(request, id, up_or_down):
    ajax = request.GET.get('ajax', False)
    try:
        book = Book.objects.get(id=id)
    except DoesNotExist:
        raise
    if book.rated_by.filter(id=request.user.id).count():
        request.user.message_set.create(message='You have already rated this')
        if ajax:
            return HttpResponse(book.get_rating_percentage())
        else:
            return HttpResponseRedirect(reverse(show, args=['book', id]))
    if up_or_down == '+':
        book.positive_ratings += 1
    else:
        book.negative_ratings += 1
    book.rated_by.add(request.user)
    book.save()
    request.user.message_set.create(message='Your rating was taken into consideration')
    #return show(request, 'book', id) BAD BAD BAD BAD!
    print "in rate_book, requst.get thing is", request.GET.get('ajax', False)
    if request.GET.get('ajax', False):
        return HttpResponse(book.get_rating_percentage())
    else:
        return HttpResponseRedirect(reverse(show, args=['book', id]))

        

def get_isbn(request):
    title = request.GET.get('book_title', None)
    if title is None:
        raise Http404
    author = request.GET.get('author', None)
    if author is None:
        index = 'title'
        value = title
    else:
        index = 'combined'
        value = '%s by %s' % (title, author)
    BookData = isbn_db.get_book_data(index, value, {'Title': 'title', 'AuthorsText': 'authors', 'Summary': 'summary'})
    return render_to_response('books/get_isbn.html',
                              RequestContext(request,
                                             {'bookdata': BookData }
                                             )
                              )

templates/books/add.html
{% extends "base.html" %}
{% load tags %}
{% block head %}{{form.media}}{% endblock %}
{% block title %}adding a {{adding_what}}{% endblock %}
{% block header %}<h1>Adding a {{adding_what}}</h1>{% endblock %}
{% block content %}
<form enctype="multipart/form-data" method="post" action="#">
<ul class="form">
{% doformul form linked specials %}
<li><input id="id_submit" type="submit" name="submit" value="Add!"/></li>
</ul>
</form>
{% endblock %}

templates/books/book_detail.html
{% extends "base.html" %}

{% block title %}Showing Book - {{book.name}}{% endblock %}

{% block head %}
<script type="text/javascript">
google.setOnLoadCallback(function() {
   rating_url = '{% url rate_book id=book.id,up_or_down="+" %}?ajax=true'
   //this url initially has a +, so that reverse works
   function rate_book(up_or_down) {
      $.get(rating_url.replace('+', up_or_down), function(data) {
         $('div.rating > span').html(data);
         updateMessages();
      });
   }
   $('#rate_positive').click(function(e) {
      e.preventDefault();
      rate_book('+');
   });
   $('#rate_negative').click(function(e) {
      e.preventDefault();
      rate_book('-');
   });
}); 
</script>
{% endblock %}

{% block header %}<h1>{{book}}
{% ifequal request.user book.created_by %}
<a href="{% url books.views.edit "book" book.id %}" class="headerlink">edit</a>
{% else %}
{% if perms.books.change_book %}
<a href="{% url books.views.edit "book" book.id %}" class="headerlink">edit</a>
{% endif %}
{% endifequal %}</h1>{% endblock %}
{% block content %}
{% if book.cover_image_authenticated and book.cover_image %}
<img src="{{ book.cover_image.url }}" class="bookimage" >
{% endif %}
<div class="author">written by {{book.authors.all|join:", "}}</div>
<div class="rating">Rating: <span>{{book.get_rating_percentage}}</span>
<a id="rate_positive" href="{% url books.views.rate_book book.id "+" %}">&#9786;</a>
<a id="rate_negative" href="{% url books.views.rate_book book.id "-" %}">&#9785;</a>
</div>
<blockquote>
{{book.blurb|linebreaks}}
</blockquote>
<div class="info">
Genre: {{book.genre}} 
{% if book.series %}| Series: {{book.series}}{% endif %}
{% if book.amazon_link %} | <a href="{{book.amazon_link}}">Amazon</a> {% endif %} | ISBN: <a href="http://isbndb.com/search-all.html?kw={{book.ISBN}}">{{book.ISBN}}</a>
</div>
<div class="reviews">
<h2>Reviews <a href="{% url books.views.add "review" %}?for_book={{book.id}}&back_to={% url books.views.show "book" book.id%}" class="headerlink">add a review</a></h2>
{% if not book.review_set.count %}
There are no reviews for this book &#9785;
{% endif %}
{% for review in book.review_set.all %}
<div class="review" id="{{review.id}}" class="review {% cycle 'review-even' 'review-odd' %}">
<strong>Reviewed by:</strong>
<a href="{% url user_profile_id whichuser=review.created_by.id %}">{{review.created_by}}</a>
<br/><strong>Rating: </strong> {{review.get_rating_display}}
<br/><blockquote>{{review.review_contents}}</blockquote>
</div>
{% endfor %}
</div>
{% endblock %}

templates/books/book_list.html
{% extends "base.html" %}
{% block title %}Showing Books{% endblock %}

{% block header %}<h1>Books</h1>{% endblock %}
{% block head %}
<script type="text/javascript">
google.setOnLoadCallback(function() {
   var url = "{{site}}{% url books_show "book" %}";
   var current_page = {{page_obj.number|default:"0"}};
   var max_page = {{paginator.num_pages|default:"0"}};
   function go(direction) {
      var newpage = current_page + direction
      if((1 <= newpage) &&  (newpage <= max_page)) {
         current_page = newpage;
         $('ul.objectlist').load(url + "?page=" + current_page + "&ajax=true");
	 $('div.pagination a').removeClass('inactive');
         if(current_page == 0)
            $('#page_previous').addClass('inactive');
         if(current_page == max_page)
            $('#page_next').addClass('inactive');
      }
   }
   $('#page_previous').click(function(e) {
      e.preventDefault();
      go(-1);
   });
   $('#page_next').click(function(e) {
      e.preventDefault();
      go(1);
   });
});
</script>
{% endblock %}
{% block content %}
    <ul class="objectlist">
      {% block ajax %}
        {% for book in object_list %}
            <li><a href="{{book.id}}"><h3 class="floatleft">{{ book }}</h3><span class="floatleft">by {{book.get_authors}}</span> {{book.genre}} &#9786;&#9785;: {{book.get_rating_percentage}} &#9998;: {{book.review_set.count}}</a></li>
        {% endfor %}
    </ul>
    {% endblock %}
    {% if is_paginated %}
    <div class="pagination">
      <a id="page_previous" {% if has_previous %} href="?page={{page_obj.previous_page_number}}" {% else %} class="inactive" {% endif %}>&lt; previous</a>
      Page {{page_obj.number}} of {{paginator.num_pages}}
      <a id="page_next" {% if has_next %} href="?page={{ page_obj.next_page_number }}" {% else %} class="inactive" {% endif %}>next &gt;</a>
    </div>
    {% endif %}
{% endblock %}

templates/books/done.html
{% extends "base.html" %}
{% block title %}Added Successfully{% endblock %}
{% block header %}<h1>The {{what_is_it|title}} was added</h1>{% endblock %}

{% block content %}
{% if request.GET.back_to %} <a href="{{site}}{{request.GET.back_to}}">Go and take a look</a>{% endif %}
{% endblock %}

templates/books/get_isbn.html
{% extends "base.html" %}
{% block title %}Choose ISBN{% endblock %}
{% block head %}
<script type="javascript" src="{{site}}/media/form_functions.js"></script>
<script type="text/javascript">
function clicked(isbn)
{
window.opener.setValueOfId('id_ISBN', isbn);
if(document.getElementById('insert_summary').checked == true)
{
window.opener.setValueOfId('id_blurb', document.getElementById(isbn+'_summary').value);
}
window.close();
}
</script>
{% endblock %}
{% block header %}<h1>Select an ISBN Number</h1>{% endblock %}
{% block content %}
Insert Summary? <input type="checkbox" id="insert_summary" />
<h3>Click to select...</h3>
{% for datum in bookdata %}
<div class="infobox" onClick="clicked({{datum.isbn}});">
<strong>Title:</strong> {{datum.title}}
<br/><strong>Authors:</strong> {{datum.authors}}
<br/><strong>Summary:</strong> {{datum.summary|truncatewords:20}}
<br/><strong>ISBN:</strong> {{datum.isbn}}
<input type="hidden" id="{{datum.isbn}}_summary" value="{{datum.summary}}"/>
</div>
{% endfor %}
{% endblock %}

templates/books/popup_close.html
{% extends "base.html" %}
{% block head %}
<script language="javascript">
window.opener.addOptionToSelectOfId('{{popup}}', '{{added_what.id}}', '{{added_what}}', true, true);
window.close();
</script>
{% endblock %}

{% block title %}Done adding {{added_what}}{% endblock %}
{% block header %}Done adding {{added_what}} {% endblock %}

{% block content %}
Your probably shouldn't be seeing this page...
{% endblock %}